export const LOGIN_USER = 'LOGIN_USER';

export const LOGOUT_USER = 'LOGOUT_USER';

export const SIGNUP_START = 'SIGNUP_START';

export const SET_BUSINESS = 'SET_BUSINESS';

export const REMOVE_BUSINESS = 'REMOVE_BUSINESS';

export const SET_FARM = 'SET_FARM';

export const REMOVE_FARM = 'REMOVE_FARM';

export const SET_CURRENT_APPLICATION = 'SET_CURRENT_APPLICATION';

export const REMOVE_CURRENT_APPLICATION = 'REMOVE_CURRENT_APPLICATION';
